#!/usr/bin/env python

import sys
import os

def __extend_module_search_path():
    script_name = os.path.abspath(__file__)
    script_dir = os.path.dirname(script_name)
    source_path = os.path.join(script_dir, '../src/')
    sys.path.append(source_path)

if __name__ == '__main__':
    __extend_module_search_path()
    from pyteryt.core.runner import main
    sys.exit(main())
